channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.6.2
  - cudatoolkit=11.0
  - pip:
      - Sphinx
      - coverage
      - flake8
      - python-dotenv>=0.5.1
      - pyarrow<4.0.0
      - torchtext
      - torch
      - pytorch_lightning
      - transformers
      - pytest
      - wandb
      - azureml-defaults
  - pip
name: nlp_env