name: project_environment
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python=3.6.9
  - 'pip>=21.0,<22'
  - pytorch==1.7.1
  - torchaudio==0.7.2
  - cudatoolkit=11.0
  - nvidia-apex==0.1.0
  - pip:
      - 'matplotlib>=3.3,<3.4'
      - 'psutil>=5.8,<5.9'
      - 'tqdm>=4.59,<4.60'
      - 'pandas>=1.1,<1.2'
      - 'theano>=1.0,<1.1'
      - 'scipy>=1.5,<1.6'
      - 'numpy>=1.10,<1.20'
      - azureml-core==1.26.0
      - azureml-defaults==1.26.0
      - azureml-mlflow==1.26.0
      - azureml-telemetry==1.26.0
      - azureml-train-restclients-hyperdrive==1.26.0
      - azureml-train-core==1.26.0
      - tensorboard==2.4.0
      - horovod==0.20.0
      - 'onnxruntime-gpu>=1.7,<1.8'
      - future==0.17.1
      - joblib
      - torchtext
      - pytorch-lightning
      - transformers
      - pytest