name: "Run tests"

on:
  push:
    branches: [ main, add-ci ]
  pull_request:
    branches: [ main, add-ci ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.6.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.12
    - name: Install dependencies
      run: |
        conda env update --file conda_dependencies.yml --name base
    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest -v
    - name: Sort imports with isort
      run: |
        conda install isort
        $CONDA/bin/isort src
    - name: Format code with flake8
      run: |
        conda install flake8
        $CONDA/bin/flake8 src
