name: "Run tests"

on:
  push:
    branches: [ main, add-ci ]
  pull_request:
    branches: [ main, add-ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install torch
      run: pip3 install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
    - name: Sort imports with isort
      run: |
        pip install isort
        isort src
    - name: Format code with flake8
      run: |
        pip install flake8
        flake8 src