name: "Run tests"

on:
  push:
    branches: [ main, add-ci ]
  pull_request:
    branches: [ main, add-ci ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.6.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.2
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file conda_dependencies.yml --name base
    - name: Test with pytest
      run: |
        pytest -v
    - name: Sort imports with isort
      run: |
        pip install isort
        isort src
    - name: Format code with flake8
      run: |
        pip install flake8
        flake8 src
