name: "Run tests"

on:
  push:
    branches: [ main, add-ci ]
  pull_request:
    branches: [ main, add-ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: nlp_env
        environment-file: conda_dependencies.yml
    - name: Test with pytest
      run: |
        conda activate nlp_env
        pytest -v
    - name: Sort imports with isort
      run: |
        pip install isort
        isort src
    - name: Format code with flake8
      run: |
        pip install flake8
        flake8 src
